on:
    push:
        branches:
            - main

name: Deploy website
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Get the latest code
              uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Build project
              run: |
                  npm install
                  npm run build

            - name: Move files to build folder
              run: |
                  mkdir build
                  cp index.html build/
                  cp -R assets/ build/
                  cp -R all-star-night/ build/

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build
